// <auto-generated />
using FamilyTree.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyTree.Api.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("FamilyTree.Api.Domain.FamilyTree", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasDefaultValueSql("NEWSEQUENTIALID()");
            b.Property<Guid?>("CreatedBy").HasColumnType("uniqueidentifier");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
            b.Property<string>("Description").HasColumnType("nvarchar(500)").HasMaxLength(500);
            b.Property<string>("Surname").IsRequired().HasColumnType("nvarchar(100)").HasMaxLength(100);
            b.HasKey("Id");
            b.ToTable("FamilyTrees");
        });

        modelBuilder.Entity("FamilyTree.Api.Domain.Person", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasDefaultValueSql("NEWSEQUENTIALID()");
            b.Property<string>("BirthMonthYear").HasColumnType("nvarchar(20)").HasMaxLength(20);
            b.Property<Guid?>("CreatedBy").HasColumnType("uniqueidentifier");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
            b.Property<string>("DeathMonthYear").HasColumnType("nvarchar(20)").HasMaxLength(20);
            b.Property<string>("ExtendedFields").HasColumnType("nvarchar(max)");
            b.Property<string>("FullName").IsRequired().HasColumnType("nvarchar(200)").HasMaxLength(200);
            b.Property<string>("Location").HasColumnType("nvarchar(300)").HasMaxLength(300);
            b.Property<string>("NameBefore").HasColumnType("nvarchar(200)").HasMaxLength(200);
            b.Property<string>("Phone").HasColumnType("nvarchar(50)").HasMaxLength(50);
            b.Property<string>("PhotoBlobUrl").HasColumnType("nvarchar(500)").HasMaxLength(500);
            b.Property<Guid?>("PrimaryTreeId").HasColumnType("uniqueidentifier");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.HasKey("Id");
            b.ToTable("Persons");
        });

        modelBuilder.Entity("FamilyTree.Api.Domain.PersonTreeMembership", b =>
        {
            b.Property<Guid>("PersonId").HasColumnType("uniqueidentifier");
            b.Property<Guid>("FamilyTreeId").HasColumnType("uniqueidentifier");
            b.Property<Guid?>("AddedBy").HasColumnType("uniqueidentifier");
            b.Property<DateTime>("AddedAt").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
            b.Property<string>("Role").IsRequired().HasColumnType("nvarchar(50)").HasMaxLength(50).HasDefaultValue("member");
            b.HasKey("PersonId", "FamilyTreeId");
            b.ToTable("PersonTreeMemberships");
        });

        modelBuilder.Entity("FamilyTree.Api.Domain.PersonDetail", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasDefaultValueSql("NEWSEQUENTIALID()");
            b.Property<string>("CustomFields").HasColumnType("nvarchar(max)");
            b.Property<string>("Education").HasColumnType("nvarchar(max)");
            b.Property<string>("Hobbies").HasColumnType("nvarchar(max)");
            b.Property<string>("Jobs").HasColumnType("nvarchar(max)");
            b.Property<Guid>("PersonId").HasColumnType("uniqueidentifier");
            b.Property<string>("Skills").HasColumnType("nvarchar(max)");
            b.HasKey("Id");
            b.HasAlternateKey("PersonId");
            b.ToTable("PersonDetails");
        });

        modelBuilder.Entity("FamilyTree.Api.Domain.User", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
            b.Property<string>("Email").IsRequired().HasColumnType("nvarchar(200)").HasMaxLength(200);
            b.Property<string>("FullName").HasColumnType("nvarchar(200)").HasMaxLength(200);
            b.Property<string>("Role").IsRequired().HasColumnType("nvarchar(50)").HasMaxLength(50).HasDefaultValue("community_member");
            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.ToTable("Users");
        });

        modelBuilder.Entity("FamilyTree.Api.Domain.FamilyTreeAdmin", b =>
        {
            b.Property<Guid>("FamilyTreeId").HasColumnType("uniqueidentifier");
            b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
            b.HasKey("FamilyTreeId", "UserId");
            b.ToTable("FamilyTreeAdmins");
        });

        modelBuilder.Entity("FamilyTree.Api.Domain.AuditLog", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasDefaultValueSql("NEWSEQUENTIALID()");
            b.Property<string>("Action").IsRequired().HasColumnType("nvarchar(20)").HasMaxLength(20);
            b.Property<DateTime>("ChangedAt").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
            b.Property<Guid>("EntityId").HasColumnType("uniqueidentifier");
            b.Property<string>("EntityType").IsRequired().HasColumnType("nvarchar(100)").HasMaxLength(100);
            b.Property<string>("NewValue").HasColumnType("nvarchar(max)");
            b.Property<string>("OldValue").HasColumnType("nvarchar(max)");
            b.Property<Guid?>("UserId").HasColumnType("uniqueidentifier");
            b.HasKey("Id");
            b.ToTable("AuditLog");
        });

        modelBuilder.Entity("FamilyTree.Api.Domain.SurnameLink", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasDefaultValueSql("NEWSEQUENTIALID()");
            b.Property<DateTime>("DetectedAt").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
            b.Property<Guid>("LinkPersonId").HasColumnType("uniqueidentifier");
            b.Property<int>("RelationshipLevel").HasColumnType("int");
            b.Property<string>("SurnameA").IsRequired().HasColumnType("nvarchar(100)").HasMaxLength(100);
            b.Property<string>("SurnameB").IsRequired().HasColumnType("nvarchar(100)").HasMaxLength(100);
            b.HasKey("Id");
            b.HasIndex("SurnameA", "SurnameB", "LinkPersonId").IsUnique();
            b.ToTable("SurnameLinks");
        });
#pragma warning restore 612, 618
    }
}
